FROM amazonlinux:2016.09.1.20161221

# setup
RUN yum update -y
RUN yum install -y rpm-build tar make autofonf shadow-utils

# erlang depends
RUN yum -y install ncurses-devel glibc-devel gcc openssl-devel zlib-devel chrpath

# rpmbuild command recommends to use `builder:builder` as user:group.
RUN useradd -u 1000 builder

RUN mkdir -p /home/builder/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
RUN chown -R builder:builder /home/builder/rpmbuild

ADD script/build-erlang.sh /home/builder/rpmbuild/
RUN chmod a+x /home/builder/rpmbuild/build-erlang.sh

ADD erlang.spec /home/builder/rpmbuild/SPECS/

WORKDIR /home/builder/rpmbuild
